runtime: nodejs18
service: default
instance_class: F2

handlers:

- url: /build/static
  static_dir: build/static
- url: /(.*\.(json|ico|js|png|jpg|css|txt))$
  static_files: build/\1
  upload: build/(.*\.(json|ico|js|png|jpg|css|txt))$
  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
- url: /.*
  static_files: build/index.html
  upload: build/index.html